name: Build and Deploy to JFrog Artifactory 

on:
  push:
    branches:
      - feature/jfrog-cli-oidc

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup JFrog CLI
      uses: jfrog/setup-jfrog-cli@v4
      env:
        JF_URL: "https://appdev1.jfrog.io/"
      with:
        oidc-provider-name: "calc"
        version: latest
        
    - name: ping JFrog
      run: |
        jf rt ping
        
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Build with Maven
      run: mvn clean compile test
      env:
        JFROG_CLI_LOG_LEVEL: DEBUG
        
    - name: Deploy to JFrog Artifactory
      run: |
        mvn clean deploy --build-name=number-adder --build-number=${{ github.run_number }}
      env:
        JFROG_CLI_LOG_LEVEL: DEBUG 
